[project]
name = "webscraping-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=4.0.0",
    "asynciolimiter>=1.2.0",
    "rnet>=2.4.2",
    "selectolax>=0.3.34",
]
